name: free_place_search
description: Free Place Search using Photon API
homepage: https://github.com/gauravmehta13/free_place_search
repository: https://github.com/gauravmehta13/free_place_search

version: 1.0.4

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true


analyzer:
  language:    
    enableSuperMixins: true  
  errors:
    # treat missing required parameters as a warning (not a hint)
    missing_required_param: warning
    # treat missing returns as a warning (not a hint)
    missing_return: warning
    # allow having TODOs in the code
    todo: ignore
# Source of linter options:
# http://dart-lang.github.io/linter/lints/options/options.html
linter:
  rules:
    - camel_case_types
    - hash_and_equals
    - iterable_contains_unrelated_type
    - list_remove_unrelated_type
    - unrelated_type_equality_checks
    - valid_regexps
