name: free_place_search
description: Free Place Search using Photon API
publish_to: "https://github.com/GauravCalidig/free_place_search.git"
version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  dio: ^4.0.5-beta1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
